### ISSUE TITLE
new developement area handling

### ISSUE THREAD

**Issue by panosatha** [Deltares-research/FloodAdapt#155]
### Kind of request

Changing existing functionality

### Enhancement Description

Right now it is not clear what happens with the new develeopment area with respect to the output visualization (buildings and aggregation areas). Same for equity output.

### Task list

- [x] Check current behaviour
- [x] Find best way to give labels to the new development area with respect to aggregation
- [x] Check how to best give ground elevation to the new area
- [x] Write tests

**Comment by GundulaW** [comment]
Please discuss with Frederique on how it was handled in the old version. Plus either Kathryn or Panos

**Comment by GundulaW** [comment]
@frederique-hub how was this handled in the old version?

**Comment by GundulaW** [comment]
discuss the low-hanging fruit solution before september deadline

**Comment by frederique-hub** [comment]
> @frederique-hub how was this handled in the old version?

In the old version, we did an overlay of the new development areas with the aggregation areas, but I'm not 100% sure. That would be the best option with regard to consistency.

**Comment by kathrynroscoe** [comment]
We may want to work with a tagged version, now that this functionality is working with HydroMT, to avoid that they make changes and it no longer works.

**Comment by panosatha** [comment]
@kathrynroscoe right now if the new developing area is overlapping with two or more aggregation areas in any of the aggregation types, there is an error and the computation is stoped with an error message from hydromt-fiat. 
How do we want to handle this?
