### ISSUE TITLE
More tests for Green Infrastructure

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#175]
### Kind of request

Changing existing functionality

### Enhancement Description

No meaningful tests have been written for GreenInfra yet, only reading and saving toml files

### Task list

- [ ] remove conversion of area units in def calculate_storage_volume since area is calculated internally and always in m2
- [ ] add test for volume calculation
- [ ] add test for sfincs adapter to assert that a volume storage input file was produced.
- [ ] visually inspect differences in SFINCS results with and without green infra

**Comment by kathrynroscoe** [comment]
Gundula is going to make a simple 'academic' example to test what is happening. Add Gundula's name to this after we add Maarten
