### ISSUE TITLE
Refactoring code

### ISSUE THREAD

**Issue by dladrichem** [Deltares-research/FloodAdapt#181]
### Kind of request

Changing existing functionality

### Enhancement Description

There are some refactoring steps that would help make the code more stable and also more modular. A few examples that come to mind:

Check if the architecture is still up-to-date
Check if interfaces are up-to-date
Add getters and setters to the properties of the classes and make the properties private
Move the models to a separate folder. Not together with the interfaces
Separate the database controller in classes for every element (measures, strategies ect.)

### Task list

- [ ] Check if the architecture is still up-to-date
- [ ] Check if interfaces are up-to-date
- [ ] Add getters and setters to the properties of the classes and make the properties private
- [ ] Move the models to a separate folder. Not together with the interfaces
- [ ] Separate the database controller in classes for every element (measures, strategies ect.)
