### ISSUE TITLE
fix output

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#199]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

error for floodmap and damage output

### Current behaviour

error for floodmap and damage output

### Desired behaviour

no error for floodmap and damage output

### Task list

- [ ] fix error related to floodmap (check with Daley)
- [ ] fix path to fiat results folder (now in <SCENARIO_NAME>\output\<SCENARIO_NAME>.csv
