### ISSUE TITLE
Create GeoJSON file for green infra measure (for aggregation area) that SFINCS adapter can read

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#200]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

SFINCS adapter cannot handle GreenInfra selection by aggregation area, linked to PR https://github.com/Deltares/FloodAdapt/pull/192

### Current behaviour

SFINCS adapter cannot handle GreenInfra selection by aggregation area

### Desired behaviour

Write out polygon file for aggregation area that sfincs adapter can handle

### Task list

- [ ] add function in SFINCS adapter to write polygon file from aggregation area to be used by hydromt-sfincs
