### ISSUE TITLE
Aligning the HydroMT-FIAT 'env_fix' branch with the 'env_fix' branches from FloodAdapt

### ISSUE THREAD

**Issue by frederique-hub** [Deltares-research/FloodAdapt#204]
### Kind of request

Changing existing functionality

### Enhancement Description

Aligning the HydroMT-FIAT 'env_fix' branch with the 'env_fix' branches from FloodAdapt

### Task list

- [ ] Create a new branch 'env_fix' in hydromt_fiat
- [ ] Run tests for the fiat integrator 
- [ ] Fix potential bugs
