### ISSUE TITLE
Elevation of new development areas

### ISSUE THREAD

**Issue by panosatha** [Deltares-research/FloodAdapt#258]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

When a new development area is added the ground elevation is 0 there.

### Current behaviour

Right now, ground elevation is assumed 0 at new developments areas.

### Desired behaviour

The elevation of the new developement areas should be derived from the DEM file.

### Task list

- [x] Add the functionality in hydromt-FIAT
- [x] Change fiat integrator accordingly

**Comment by frederique-hub** [comment]
This can be added here: https://github.com/Deltares/hydromt_fiat/blob/807d0b179b6d8014817e17ca0a4ace24096cac81/hydromt_fiat/workflows/exposure_vector.py#L808

**Comment by kathrynroscoe** [comment]
Mario worked on this. Should be merged soon.
