### ISSUE TITLE
create time-series hmtl for water levels at obervation stations

### ISSUE THREAD

**Issue by panosatha** [Deltares-research/FloodAdapt#272]
### Kind of request

Adding new functionality

### Enhancement Description

For the observation stations (including gauge locations when defined), we want to see the computed timeseries.
The HTML(s) should be produced when we run a scenario and be saved in the output.
The locations should be included in the site.toml and then be added in the SFINCS toml?
Should be possible to add multiple gauges (a list).

### Task list

- [x] add obs_points to site.toml
- [x] add observation locations to SFINCS model in SFINCS Adapter and preprocess SFINCS
- [x] add plot_wl function in postprocess sfincs and save html in Scenario Flooding folder
- [x] add icon and pop up in mapbox (definitely Scenario tab and perhaps also compare tab?)
        - [ ] alle per scenario copieren when select scenario
        - [ ] code van Maarten in output
- [x] app.startup gdf van alle locations ophalen
- [ ] add observed timeseries if available

**Comment by kathrynroscoe** [comment]
This is existing in some branch. Gundula will be involved in the timeseries generation, Gundula will handle the html production and the gauge showing up on the map, and the pop-up. When we prioritize this, add Gundula to the issue. How precisely to do this is to be discussed.
