### ISSUE TITLE
With transposing the metrics data, the benefits didn't work anymore

### ISSUE THREAD

**Issue by dladrichem** [Deltares-research/FloodAdapt#280]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

If you update to main, the benefits tab doesn't work anymore

### Current behaviour

Error

### Desired behaviour

No error

### Task list

- [ ] fix the issue
