### ISSUE TITLE
RP flood map calculation

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#286]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

RP flood map calculation

### Current behaviour

RP flood map calculation

### Desired behaviour

RP flood map calculation

### Task list

- [ ] keep spiderweb files in event folder and copy to simulation folder
- [ ] check if spiderwebfile already exists in event folder and re-use if possible
- [ ] delete SFINCS simulation folder for risk scenario

**Comment by GundulaW** [comment]
linked to #277
