### ISSUE TITLE
Add ERROR if SFINCS did not finish correctly

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#287]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

Geotiff is created and FIAT is run even though SFINCS has crashed and the output includes rubbish values

### Current behaviour

Geotiff is created and FIAT is run even though SFINCS has crashed and the output includes rubbish values

### Desired behaviour

stop scenario run if SFINCS has crashed

### Task list

- [ ] for post-processing_sfincs: add if else clause checking for "Maximum depth of 100.0 m reached!!! Simulation stopped." in the sfincs log file, meaning that the simulation has crashed
- [ ] add similar if else clause for running FIAT
- [ ] add error statement in floodadapt log file
- [ ] add error pop-up window in GUI

**Comment by kathrynroscoe** [comment]
Many ways SFINCS can crash. We only give an error if it becomes unstable. Maybe we better can give a message if all ran correctly.

**Comment by savente93** [comment]
Marked as done so closing
