### ISSUE TITLE
Add error if height or volume of GreenInfra is zero

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#288]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

When testing GreenInfra I noticed that hydromt-sfincs crashes when the height or volume provided are zero. 

### Current behaviour

hydromt-sfincs crashes when the height or volume provided are zero. 

### Desired behaviour

Provide an error message and do not allow a measure with zero height or volume to be added. 

### Task list

- [ ] add a check in the GreenInfra class whether volume or height are zero. 
- [ ] provide error pop-up in GUI
- [ ] add error message in log file
