### ISSUE TITLE
calculate aggregated benefits

### ISSUE THREAD

**Issue by panosatha** [Deltares-research/FloodAdapt#298]
### Kind of request

Adding new functionality

### Enhancement Description

Instead of only producing total benefits, benefits should be calculated per aggregation areas ( any type of aggregation provided)

### Task list

- [ ] update code to calculate aggregated benefits
- [ ] write unit tests
- [ ] check with front-end developements for final changes
