### ISSUE TITLE
Add hurricanes to event set

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#303]
### Kind of request

None

### Enhancement Description

Add hurricanes to event set

### Task list

- [ ] make updated events set
- [ ] when running hurricane event, check first if spw file exists in event folder
- [ ] if not add
- [ ] copy spw file to simulation folder
