### ISSUE TITLE
Overall stuff meta issue

### ISSUE THREAD

**Issue by dladrichem** [Deltares-research/FloodAdapt#313]
### Kind of request

Adding new functionality

### Enhancement Description

We want better unit tests

### Task list

- [ ] Add unit test for measures #272 
- [ ] Add unit test for events #312 
- [ ] Add unit tests for projectios #310
