### ISSUE TITLE
nan values in hazard map

### ISSUE THREAD

**Issue by panosatha** [Deltares-research/FloodAdapt#326]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

Now we fill the nan values with zeros, which can be error prone for specific areas.

### Current behaviour

Currently the water level map from SFINCS is loaded and it has nan values at the dry cells, but there is no FillValue set in the netcdf, which then does not allow FIAT to correctly interpret the nan values.

### Desired behaviour

The values in the hazard map that are dry should have nan values instead of zeros.

### Task list

- [x] Check if this is a FloodAdapt or HydroMT-FIAT issue

**Comment by panosatha** [comment]
This was fixed with the new FIAT exectuable https://github.com/Deltares/Delft-FIAT/releases/tag/v0.1.0rc2 and the part where zeros were filled in is now taken out.
