### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by dladrichem** [Deltares-research/FloodAdapt#329]
### Description

General meta issue for refactoring stages

Some additional tasks:
- [ ] Check if the architecture is still up-to-date
- [ ] Check if interfaces are up-to-date
- [ ] Add getters and setters to the properties of the classes and make the properties private
- [ ] Move the models to a separate folder. Not together with the interfaces
- [ ] Separate the database controller in classes for every element (measures, strategies ect.)

### Issue list

Refactor Models:
- [ ] pydantic validators #226`
- [ ] Change to current pydantic version #170 
- [ ] Refactoring unit conversions #189

Multiprocessing:
- [ ] running SFINCS in background/queuing scenarios #125

Refactor SFINCS adapter:
- [ ] Reuse dbs_controller function to get obs_points in SFINCS adapter #320  
- [ ] Refactor workflow overland and offshore SFINCS model #319 
- [ ] Update with new SFINCS exit when crashing #311

Refactor FIAT:
- [ ] New development area aggregation handling #318
