### ISSUE TITLE
Add units to results read with SFINCS Adapter 

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#332]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

read_zsmax function does not have units from SFINCS model, which FIAT needs

### Current behaviour

read_zsmax function does not have units from SFINCS model, which FIAT needs

### Desired behaviour

add units to read_zsmax function in SFINCS adapter

### Task list

- [ ] add units to read_zsmax function in SFINCS adapter, check what units should be called
- [ ] carefully test that this does not screw up anything else
- [ ] is the same necessary for read_points?
- [ ] remove quick and dirty fix when reading SFINCS results for FIAT

**Comment by dladrichem** [comment]
SFINCS always outputs meters

**Comment by savente93** [comment]
Marked as done so closing
