### ISSUE TITLE
fix SLR in event sets

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#341]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

for nearshore_hstorical and probably also synthetic SLR is added n times where n is the number of events. This does not happen for hurricanes

### Current behaviour

for nearshore_hstorical and probably also synthetic SLR is added n times where n is the number of events. This does not happen for hurricanes

### Desired behaviour

Add SLR only once

### Task list

- [x] debug hazard.add_wl()
- [x] update test to check correct SLR is added
