### ISSUE TITLE
Use tide amplitude from site.toml in event pop up

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#393]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

It's currently overwritten in events.py

### Current behaviour

It's currently overwritten in events.py

### Desired behaviour

use tide amplitude from site.toml

### Task list

- [ ] it's probably already set as a GUI variable in app.py, please check
