### ISSUE TITLE
The selected huricane is not always actually selected

### ISSUE THREAD

**Issue by dladrichem** [Deltares-research/FloodAdapt#400]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

If you immediately click OK and not on a hurricane name in the table, it will crash. Also, if you filter first, and then click OK, it also crashes. Basically, it always crashes if you don't click on a hurricane in the table

### Current behaviour

The table shows up highlighting the first hurricane in the table. However, as long as you don't click in the table, nothing is actually selected yet. 

### Desired behaviour

Either, the first (which is the one that is highlighted) should be selected by default. Or, nothing should be highlighted when the window opens

### Task list

- [ ] Check if it is possible to not highlight anything
- [ ] If not, select the first by default
- [ ] Check that if you apply a filter and the table changes, whether it still works
