### ISSUE TITLE
Split mandatory and not mandatory metrics

### ISSUE THREAD

**Issue by dladrichem** [Deltares-research/FloodAdapt#401]
### Kind of request

Changing existing functionality

### Enhancement Description

Some metrics are mandatory since they are used by other parts of the system (i.e. the benefits calculation using the expected damages). These should always be calculated. Some other metrics are only indicative to the user. These are not mandatory and also can be changed/added/removed by the user. These two groups should be in different files. 

Side note, it is mandatory to calculate these metrics. It is not mandatory to also show them in the GUI

### Task list

- [ ] Check which metrics are mandatory
- [ ] Split the file
- [ ] Implement reading and stacking both files
