### ISSUE TITLE
Editing a measure shouldn't be possible if it is part of a strategy

### ISSUE THREAD

**Issue by dladrichem** [Deltares-research/FloodAdapt#402]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

Add a measure to a strategy and then edit/delete the measure

### Current behaviour

Measures can still be edited even though they are part of a strategy

### Desired behaviour

If you add a measure to a strategy, it should not be possible to edit the measure anymore. This holds for both the parameters and the geometry. Also, just to be sure, check the connection between the strategy and scenario. Otherwise, that would break the connection between the measure and scenario

### Task list

- [ ] Implement
- [ ] Check that the geometry is not editable
- [ ] Check that the parameters are not editable
- [ ] Check the connection between strategies and scenario's

**Comment by savente93** [comment]
Marked as done so closing
