### ISSUE TITLE
Changing background layers crashes the app after having selected the measures tab

### ISSUE THREAD

**Issue by dladrichem** [Deltares-research/FloodAdapt#403]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

- Change the background layer first, this should work fine
- Then go to the measures tab
- Let the measures tab load
- Change the background layer again. Now it crashes

### Current behaviour

When changing background layers once you've been to the measures tab it breaks

### Desired behaviour

Don't crash. Seems to have something to do with the snapper

### Task list

- [x] Make it not crash

**Comment by savente93** [comment]
Marked as done so closing
