### ISSUE TITLE
Snapping to grid should only be done when selecting a measure

### ISSUE THREAD

**Issue by dladrichem** [Deltares-research/FloodAdapt#405]
### Kind of request

Changing existing functionality

### Enhancement Description

When the measures tab is opened, it snaps all measures that can be snapped to the grid. This is done by default. When the 'show sfincs snapper' is not selected, it might not even be necessary to create this layer. Also, when you have multiple things that needs to be snapped, it takes a while. Therefore, change this to that it only snaps the layer once 'show sfincs snapper' is selected and then only for the selected measure

### Task list

- [ ] Implement the check for the 'show sfincs snapper' checkbox
- [ ] Implement that it only the measure you select is snapped
- [ ] Check that it works in both directions. When you first select a measure with the 'show sfincs snapper' off and then turn it on, and when you switch measures with the 'show sfincs snapper' on
