### ISSUE TITLE
Elevate buildings with base flood elevation for nan values (-9999)

### ISSUE THREAD

**Issue by panosatha** [Deltares-research/FloodAdapt#407]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

it is not clear what happens when the BFE values are -9999 and the options is raise buildings base on flood elevation.

### Current behaviour

It seems that the actual -9999 values is used for the flood elevation

### Desired behaviour

If there is no flood elevation there should be no raising of the buildings.

### Task list

- [x] Check behaviour
- [x] Implement change in hydromt-fiat

**Comment by panosatha** [comment]
The check for finding properties to elevate is finding properties that are bellow the bfe + raiseby level. If bfe is -9999 this will essentially mean that no properties are chosen. Moreover, actual nan values where no information are available are currently handled well.
