### ISSUE TITLE
Raise by DATUM is currently increasing the elevation above ground and not datum

### ISSUE THREAD

**Issue by panosatha** [Deltares-research/FloodAdapt#409]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

When raising buildings above datum the raise is done aboe ground level and not datum!

### Current behaviour

When raising buildings above datum the raise is done aboe ground level and not datum!

### Desired behaviour

The raise should be done above datum.

### Task list

- [x] Change method in hydromt-fiat
- [x] update tests
