### ISSUE TITLE
Copying a projection with new development does not work

### ISSUE THREAD

**Issue by panosatha** [Deltares-research/FloodAdapt#411]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

When you have created a projection with new development area and then you try to copy it you get an error related with the geojson file missing.

### Current behaviour

When you have created a projection with new development area and then you try to copy it you get an error related with the geojson file missing.

### Desired behaviour

When you have created a projection with new development area and then you try to copy it the spatial file describing the extents should correctly be copied and the object model should correctly be updated.

### Task list

- [ ] Check where it goes wrong when copying
- [ ] Correct the copying method
- [ ] Make unit tests

**Comment by kathrynroscoe** [comment]
this is duplicate with #553
