### ISSUE TITLE
system crashes when observation station has a special character

### ISSUE THREAD

**Issue by panosatha** [Deltares-research/FloodAdapt#418]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

Including ¨ (umlauts) in the name of an obsrvation station makes floodadapt break at the SFINCS postprosessing step.

### Current behaviour

Using special characters in the observation station name in the site.toml, breaks the workflow, since hydromt-sfincs cannot read the SFINCS model anymore (more specifically the issue is reading in the sfincs.obs file).

### Desired behaviour

Add validators in the pydantic model for the site object to make sure that special characters are not included in the names of the observations stations. This way even if the user has manually change something, the validator would be run during startup and give an informative message.

This could be an issue for other parameters!

### Task list

- [x] Check for which other parameters this is true
- [ ] Write site.toml validators
- [ ] Write tests

**Comment by savente93** [comment]
how would this work if someone enters a name like "松阿察河" (river in china)? In general doing these kinds of conversions can be dangerous if you don't know how your input space is structured. For example, if we would just Latinise these we'd get into trouble with things like: 
 问 = wèn = to ask
 吻 = wěn = to kiss

Now we could require that input is ASCII encoded, but I think this will be quite an impediment to the adoption of FA outside of Anglicised regions.  

I'm assuming that the text in the `sfincs.obs` file is mostly either decorative (labels) or used as some kind of unique identifier. Would it be at all feasible to ask SFINCS to allow `utf-8` text in the `obs` file? I feel like that's the better solution here, as it would benifit the adoption of both sfincs and FA

**Comment by savente93** [comment]
(just playing devils advocate here, hope that didn't come off too critical)

**Comment by savente93** [comment]
having gone through the SFNICS docs as best I can, I found this page about the input formats: https://sfincs.readthedocs.io/en/latest/parameters.html#input-files Here any text based format is listed as `asc` which I take to mean ASCII which means that the answer to " Check for which other parameters this is true" is basically "any text that SFNICS accepts"
