### ISSUE TITLE
FA model builder

### ISSUE THREAD

**Issue by panosatha** [Deltares-research/FloodAdapt#419]
### Kind of request

Adding new functionality

### Enhancement Description

Create a workflow to create a FloodAdapt model using SFINCS and FIAT models.

### Task list

- [ ] Identify parts that can be automatically read from the models with HydroMT and what does the user need to provide
- [ ] Create script with the workflow
- [ ] Test creation with a couple of case studies
