### ISSUE TITLE
site toml issues

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#422]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

small issues to fix

### Current behaviour

small issues to fix

### Desired behaviour

small issues to fix

### Task list

- [x] remove reference water level.reference as it is not used
- [x] remove ambient pressure, this should be included in the template model
- [x] obs point should be made optional (check what happens to station?)
- [x] rename obs_station to tide_gauge, and remove reference water levels from it
- [x] rename risk.flooding_threshold to flooding_frequency.threshold
- [x] tide_gauge should have a source attr
- [x] river should be made optional
- [ ] roads should be optional
