### ISSUE TITLE
when checking for existing hazard run it does not check whether the timesereis is the same

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#440]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

When a hazard simulation is exactly the same apart from  the data in the timeseries file, it will think this hazard has already been simulated and will re-use old data, even though the data in the timeseries file is different.

As a result, the following can happen: The user tries scenarios with different timeseries, for example, increasing the discharge. The user thinks the results should be different but FloodAdapt reuses the old floodmap.

### Current behaviour

When a hazard simulation is exactly the same apart from  the data in the timeseries file, it will think this hazard has already been simulated and will re-use old data, even though the data in the timeseries file is different

### Desired behaviour

Add a check to compare timeseries when these are used in the event

### Task list

- [ ] Add a check to compare timeseries when these are used in the event
