### ISSUE TITLE
Wrong volume when importing GreenInfra polygons from file

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#441]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

When importing multiple polygons for GreenInfra from file the total volume is too small.

### Current behaviour

green_infrastructure.calculate_polygon_area only calculates the area of the first polygon and not the total area of all polygons.

### Desired behaviour

It should use the total area of all polygons

### Task list

- [x] calculate total area of all polygons
