### ISSUE TITLE
Carefully check all file imports and their behaviour

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#444]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

File imports are not carefully tested

### Current behaviour

Some unexpected behaviour

### Desired behaviour

as expected

### Task list

- [ ] discuss which file imports to test and how
- [ ] discuss the functionality we expect

**Comment by kathrynroscoe** [comment]
This is a more general solution to the problem with #553
