### ISSUE TITLE
output deleted when running many files

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#452]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

Kiara is running multiple scenarios via our API function scenario.run() through a python script.
She has the issue that SFINCS outputs (netcdf and geotiff) are cleared (files are empty) after finishing ~12 scenarios. The metrics and geojson files with building footprints etc. remain in place.

Her python script is in <svn>\Database\rijnmond\My_FloodAdapt.py

Her database is also on the svn. 

### Current behaviour

See above

### Desired behaviour

not delete outputs LOL

### Task list

- [ ] check if something goes wrong when copying hazard data from an existing scenario? 
- [ ] Check, if this only happens outside of FA or also in through the GUI?
