### ISSUE TITLE
Install via Pixi

### ISSUE THREAD

**Issue by Jaapel** [Deltares-research/FloodAdapt#485]
### Kind of request

Adding new functionality

### Enhancement Description

Installing via the python3.10-win-amd wheels only is difficult for people with different environments (and for sure the cloud!).
Using pixi (also used in other projects / products) can help make this easier for developers and speed up the ci.

### Task list

- [x] write pixi.toml with requirements, versions
- [ ] create important tasks in pixi
- [ ] (optional) use these tasks in the ci

### Use case

Installing FloodAdapt backend dependencies in a non-windows environment.

**Comment by kathrynroscoe** [comment]
This is going to make it easier for people to install FA (python version) and to have it running online

**Comment by savente93** [comment]
Pixi does not support authenticated/private repositories so until the FA Quadtree functionality from the SFINCS team is migrated to the public repository this is blocked
