### ISSUE TITLE
Pytest discovery very slow

### ISSUE THREAD

**Issue by Jaapel** [Deltares-research/FloodAdapt#492]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

`pytest --co`

### Current behaviour

Collection of tests is very slow

### Desired behaviour

Collection of tests is fast

### Task list

- [ ] refactor fixtures to be lazy (executed once called)
- [ ] get rid of unneccesary global variables

**Comment by kathrynroscoe** [comment]
no longer the case
