### ISSUE TITLE
Run (and test) FloodAdapt on other OS than windows

### ISSUE THREAD

**Issue by Jaapel** [Deltares-research/FloodAdapt#497]
### Kind of request

Adding new functionality

### Enhancement Description

I want to run FloodAdapt on Linux

### Task list

- [ ] environment installer that works outside of windows (pixi?)
- [ ] make sfincs executable configurable
- [ ] execute tests on a different environment (GitHub actions or Teamcity)

### Use case

Developing on linux, running in any containerized system

**Comment by kathrynroscoe** [comment]
connected to #527
