### ISSUE TITLE
publish automatically updated API docs 

### ISSUE THREAD

**Issue by savente93** [Deltares-research/FloodAdapt#510]
### Kind of request

None

### Enhancement Description

Currently thee is no documentation about the API of the flood adapt backend. For people wanting to use the backend without the frontend this is very inconvenient 

### Task list

- [ ] decide where the new docs should live
- [ ] migrate docs to there
- [ ] upade api CI workflow to publish to there 

### Use case

developer instead of click user

### Additional Context

Things that have been considered: 

1. using quarto is probably a good idea since the main docs are also built with that and having uniform tools is a good thing. The API can then be created with [quartodoc](https://github.com/machow/quartodoc)
2. Having multiple different sites hosted on github pages in the same repo is not possible
3. we considered to use the github wiki for the api docs, but these come with some very sever limitation such as not being able to group pages into folders or subfolders
4. One solution currently being considered is to move the user docs to the GUI repo, and have the API docs hosted here.

**Comment by LuukBlom** [comment]
put it as a tab `api reference` in the user docs
