### ISSUE TITLE
Improve Video workflow for docs

### ISSUE THREAD

**Issue by Santonia27** [Deltares-research/FloodAdapt#545]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

The videos should be moved from youtube to vimeo

### Current behaviour

currently videos are hosted on youtube and can only be accessed by Katheryn >> bottleneck

### Desired behaviour

move the videos to vimeo so we can all access it 

### Task list

- [ ] move videos to vimeo
