### ISSUE TITLE
FA database builder assumes FIAT model always has roads

### ISSUE THREAD

**Issue by panosatha** [Deltares-research/FloodAdapt#547]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

If someone tries to create a database using a FIAT model without roads they will get an error:
![image](https://github.com/user-attachments/assets/af06b076-dc30-4be8-9aec-4e870f675003)

### Current behaviour

the update_fiat_elevation method assumes that there are always roads in the FIAT model

https://github.com/Deltares-research/FloodAdapt/blob/b6789521d298fa9f8a6146febd3d65446c712084/flood_adapt/database_builder/create_database.py#L1003-L1005

### Desired behaviour

There should be an update of the elevations of all object, without any hardcode reference to file names and paths.

### Task list

- [ ] check functionality of hydromt-FIAT
- [ ] update method
- [ ] test
