### ISSUE TITLE
new development area shapefile not copied in projection folder

### ISSUE THREAD

**Issue by panosatha** [Deltares-research/FloodAdapt#553]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

When a projection with new development area is created the vector file used as input to define the areas is not copied in the database projection folder. 

### Current behaviour

When a projection with new development area is created the vector file used as input to define the areas is not copied in the database projection folder. The path to the actual input file is saveed in the object toml.

### Desired behaviour

The input geospatial file should be first checked (if it is a polygon etc.)then copied to the folder, and then that file should be references in the object toml

### Task list

- [ ] add checks for file format
- [ ] adjust workflow to copy file
- [ ] add database file in the object toml

**Comment by LuukBlom** [comment]
This is fixed in the refactor
