### ISSUE TITLE
cannot run risk with RPs bellow 1 year

### ISSUE THREAD

**Issue by panosatha** [Deltares-research/FloodAdapt#554]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

if an RP of less than a year or in general a decimal RP is configured in the site.toml an error will be returned :
`Unknown format code 'd' for object of type 'float'`

### Current behaviour

https://github.com/Deltares-research/FloodAdapt/blob/369e4cba95709dd7400abaa18cd049494f0bfc73/flood_adapt/object_model/hazard/hazard.py#L699

this part assumes that the RP is always an integer.

### Desired behaviour

It could be desired that we have RPs bellow 1 year so we should allow for this option.

### Task list

- [ ] check all parts that this assumption is used
- [ ] updated workflow
- [ ] write tests
