### ISSUE TITLE
Floodmap geotiffs are saved in the projection of the DEM in the FA static folder, should be the SFINCS coordinate system

### ISSUE THREAD

**Issue by panosatha** [Deltares-research/FloodAdapt#568]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

The geotiff flood depth map that is saved as a sfincs post-processing step has a geographic projection.

### Current behaviour

The geotiff flood depth map that is saved as a sfincs post-processing step has a geographic projection.

### Desired behaviour

Flood maps should have projected coordinates systems. The one from SFINCS should be used.

### Task list

- [ ] Check workflow to find where to change
- [ ] Test

**Comment by LuukBlom** [comment]
Important if we want to have the area clac in the beta release

**Comment by Santonia27** [comment]
is this still relevant? 
at least in the models that I ran in Trinidad and Rio de Janeiro the geotiff flood depth map in the output folder is in the reprojected projection. 

Or is this related to another file?

**Comment by Santonia27** [comment]
geotiffs are written in hydromt sfincs. I can re-open the written geotiff file and reproject it and overwrite it. 
Possibly better to include this into hydromt sfincs at one point as an option to reproject before writing?
