### ISSUE TITLE
Databasebuilder Roads crs

### ISSUE THREAD

**Issue by Santonia27** [Deltares-research/FloodAdapt#581]
### FloodAdapt version checks

- [x] I have checked that this issue has not already been reported.
- [x] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

The database builder changes the road crs to 4326 no matter what. 
Sometimes the model crs is different and then the roads don't match the model anymore. The step of the crs conversoin should not take place or instead of hard code the crs, use the fiat model crs.

### Current behaviour

- [x] change hard coded code that changes road crs to 4326

### Desired behaviour

- [x] change hard coded code that changes road crs to 4326

### Task list

- [x] change hard coded code that changes road crs to 4326
