### ISSUE TITLE
Databasebuilder Road metrics are written even when model has no roads

### ISSUE THREAD

**Issue by Santonia27** [Deltares-research/FloodAdapt#582]
### FloodAdapt version checks

- [x] I have checked that this issue has not already been reported.
- [x] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

Building a database with a fiat model without roads causes the scenario rnu to fail because the metrics point to the road_config and road metrics, spatial2.gpkg (site.toml). 

### Current behaviour

Building a database with a fiat model without roads causes the scenario ru to fail because the metrics point to the road_config and road metrics. 

### Desired behaviour

Road metrics should not be written into the database if no roads are in the model

### Task list

- [ ] add code in add_metrics to exclude road metrics
