### ISSUE TITLE
Automated changelog

### ISSUE THREAD

**Issue by savente93** [Deltares-research/FloodAdapt#583]
### Kind of request

Adding new functionality

### Enhancement Description

In our definition of done for the beta release it is mentioned that we need to have automated change log generation. 

### Task list

- [ ] Agree on a format
- [ ] implement the tooling necessary
- [ ] enforce the format

### Additional Context

A very well used system for this is to format the commit messages on main according to the conventional commit message standard which can then be easily parsed by a tool. The specification is there https://www.conventionalcommits.org/en/v1.0.0/ Personally I also have had very pleasant experiences using https://github.com/orhun/git-cliff and https://github.com/KeisukeYamashita/commitlint-rs to help make this workflow a lot easier, so I would recommend using those. I have developed some workflows on my personal repository that we can use.
