### ISSUE TITLE
rainfall magnifier in event not working

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#601]
### FloodAdapt version checks

- [x] I have checked that this issue has not already been reported.
- [x] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

rainfall increase in event.toml remains zero even if another percentage has been defined

### Current behaviour

rainfall increase in event.toml remains zero even if another percentage has been defined

### Desired behaviour

obvious

### Task list

- [ ] check in hazard refactor
