### ISSUE TITLE
Database Builder current projections and no_measures strategies missing

### ISSUE THREAD

**Issue by Santonia27** [Deltares-research/FloodAdapt#614]
### FloodAdapt version checks

- [x] I have checked that this issue has not already been reported.
- [x] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

When creating a database the current projections are missing and no_measures strategies

### Current behaviour

When creating a database the current projections are missing and no_measures strategies

### Desired behaviour

current projections and no_measures strategies are created

### Task list

- [ ] bugfix create missing input

**Comment by Santonia27** [comment]
\AppData\Local\miniforge3\lib\site-packages\flood_adapt\system 
The system folder is missing, hence the code crashes at setting up the Settings(). 
Is this folder missing just for me or also others ?

**Comment by Santonia27** [comment]
due to missing system folder but is handled by the installer
